<h2 >Služby - detail</h2>
<!--<hr>-->
<div class="col-lg-5">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title"><i class="fa fa-minus-square"></i> Detail služby  <?php echo $this->sluzba['doklad_cislo'];?></h3>
		</div>
		<div class="panel-body">

			<div class="row">
				<fieldset>
					<legend><i class="fa fa-calendar"></i> Dátum služby</legend>

					<div class="col-lg-6">
						Dátum od:
						<?php echo date("d.m.Y", strtotime($this->sluzba['datum_sluzby_od_d'])); // render the user name field here ?>
					</div>

					<div class="col-lg-6">
						Dátum do:
						<?php echo date("d.m.Y", strtotime($this->sluzba['datum_sluzby_do_d'])); // render the user name field here ?>
					</div>
				</fieldset>
			</div>


			<div class="row">
				<fieldset>
					<legend><i class="fa fa-truck"></i> Zákazník</legend>
					<div class="col-lg-6">
						Zákazník:
						<?php echo $this->ciselniky['zakazniciSluzbyModel']->getNazov($this->sluzba['zakaznik_enum']); // render the user name field here ?>
					</div>
			</div>

			<div class="row">
				<div class="col-lg-6">
					Štiepenie:
					<?php echo $this->sluzba['miesto_stiepenia']; // render the user name field here ?>
				</div>
				</fieldset>
			</div>

			<div class="row">
				<fieldset>
					<legend><i class="fa fa-cubes"></i> Množstvo</legend>
					<div class="col-lg-6">
						Váha:
						<?php echo number_format($this->sluzba['q_tony'], 2, ",", " ").' t'; // render the user name field here ?>
					</div>


					<div class="col-lg-6">
						Objem:
						<?php echo number_format($this->sluzba['q_prm'], 2, ",", " ").' PRM'; // render the user name field here ?>
					</div>

			</div>
			<div class="row">


				<div class="col-lg-6">
					Motohodiny:
					<?php echo number_format($this->sluzba['q_motohodiny'], 2, ",", " ").' MH'; // render the user name field here ?>
				</div>
				</fieldset>
			</div>



			<div class="row">
				<fieldset>
					<legend><i class="fa fa-fw fa-cogs"></i> Stroj</legend>
				<div class="col-lg-12">
					Využitý stroj:
					<?php echo $this->ciselniky['strojeModel']->getNazov($this->sluzba['stroj_enum']); // render the user name field here ?>
				</div>
					</fieldset>
			</div>

			<div class="row">
				<fieldset>
					<legend><i class="fa fa-info-circle"></i> Doplňujúce informácie</legend>
					<div class="col-lg-6">
						Stav:
						<?php echo $this->ciselniky['transakcieStavyModel']->getNazov($this->sluzba['stav_transakcie']); // render the user name field here ?>
					</div>
					<div class="col-lg-6">
						Chyba:
						<?php if ($this->sluzba['chyba'] == 1 ) echo 'áno';
						else echo 'nie'; // render the user name field here ?>
					</div>
			</div>
			<br>
			<div class="row">

				<div class="col-lg-12">
					Poznámka:
					<?php if ($this->sluzba['poznamka'] == '' || $this->sluzba['poznamka'] == '0' ) echo 'žiadna poznámka';
					else echo $this->sluzba['poznamka']; // render the user name field here ?>
				</div>
				</fieldset>
			</div>



			<br>

			<div class="row">


				<div class="col-lg-6 tright">

					<?php
					/*

					$merna_jednotka = $this->ciselniky['zakazniciSluzbyModel']->getMernaJednotka($this->sluzba['zakaznik_enum']);

					if ($merna_jednotka == 1 )
						echo '<a class="btn-info btn" href="'.$this->url(array("controller"=>"Sluzby", "action"=>"printton", "id"=>$this->sluzba['t_sluzby_id'], "fromAction" => "list",
								)).'" target="_blank">Tlačiť</a>'
					//                <!--                    printton-->
					?>

					<?php  if ($merna_jednotka == 2 )
						echo '<a class="btn-info btn" href="'.$this->url(array("controller"=>"Sluzby", "action"=>"printprm", "id"=>$this->sluzba['ts_sluzby_id'], "fromAction" => "list",
								)).'" target="_blank">Tlačiť</a>'
					//                <!--                   printprm-->
					?>
					<?php  if ($merna_jednotka == 3 )
						echo '<a class="btn-info btn" href="'.$this->url(array("controller"=>"Sluzby", "action"=>"printm3", "id"=>$this->sluzba['ts_sluzby_id'], "fromAction" => "list",
								)).'" target="_blank">Tlačiť</a>'
					//                <!--                    printm3-->
					//                               */ ?>



				</div>

				<div class="col-lg-6">
					<a href="<?php echo $this->url(array(
							'controller' => $this->fromController,
							'action' => $this->fromAction,
							'id' => $this->fromId
					), null, true) ?>"  type="button" class="btn btn-warning form-control">Späť</a>
				</div>



			</div>

		</div>
	</div>