<?php

$this->inlineScript()->appendFile($this->baseUrl().'/js/bootstrap.min.js');
$this->inlineScript()->appendFile($this->baseUrl().'/js/jjquery.js');
$this->inlineScript()->appendFile($this->baseUrl().'/js/table_features.js'); //tuto su prepocty priemer a sum
//$this->inlineScript()->appendFile($this->baseUrl().'/js/fancy_table_test.js');


?>

<br /><br />
<div id="view-content">
    <h1>Profil</h1>
	<p>Tu si budete môcť nastaviť všetky potrebné nastavenia vlastného profilu.</p>
    <p>Napríklad:</p>
    <ul>
        <li>heslo</li>
        <li>meno</li>
        <li>alebo niečo úplne iné</li>
    </ul>
</div>

<h3>Navigácia</h3>
<?php
    $container = new Zend_Navigation();
    $this->navigation($container);

        $container->addPage(
            array(
                'label'      => 'Nastenka',
                'module'     => 'default',
                'controller' => 'profil',
                'action'     => 'index',
                'pages'      =>
                    array(
                        array(
                            'label'      => 'Nastenka',
                            'module'     => 'default',
                            'controller' => 'profil',
                            'action'     => 'index'
                        ),
                        array(
                            'label'      => 'Nastenka',
                            'module'     => 'default',
                            'controller' => 'profil',
                            'action'     => 'index'
                        ),array(
                        'label'      => 'Nastenka',
                        'module'     => 'default',
                        'controller' => 'profil',
                        'action'     => 'index'
                    ),
                    )
            )


                    );

    //Finally, echo the breadcrumb!
    echo '<div>';
    echo 'You are in: '.$this->navigation()->breadcrumbs()->setLinkLast(false)->setMinDepth(0)->render();
    echo '</div>';
php?>


<!--for display text and submit fields i use viewHelpers it's very comfortable and easy way.-->
<div class="submit_area">
    <?php echo $this->formText('message', 'empty', array('size' => 32, 'id' => 'message')) ?>
    <?php echo $this->formSubmit('submitTo', 'submit', array('id' => 'submitTo')) ?>

    <div class="show-msg">TRalala</div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

<script type="text/javascript">
    //for send data i'll use jquery library
    $(document).ready(
        function(){

            //By clicking on button submit condition makes validate on empty message
            //unless field message will be not empty  , the programm make send data to
            //controller via ajax
            $("#submitTo").click(function() {
                //moje kodis
                //$(".show-msg").html("víno");

                var message = $('#message').val();
                //var message = 'Bitch I might be!';
                if (message != '') {
                    //run ajax
                    $.post('vydaje/getvydaje',
                        {'message' : message},

                        //callback function
                        function (respond) {


                            $(".show-msg").html(respond);


                        }
                    );
                }

            });





        }
    );

    </script>


<script>




</script>





    <div id=".col-lg-12"  class="table-responsive">
        <table id="fancy_table"  class="table table-striped table-hover">

            <thead>
            <tr class="tableizer-firsrow">
                <!--    <th>ID</th>-->
                <!--        <th>doklad číslo</th>-->
                <th class="no-print">Detail</th>
                <th>Dátum</th>
                <th>Lokalita</th>
                <th class="col-podsklad">Sklad</th>
                <th>Dodávateľ</th>
                <th>Prepravca</th>
                <!--    <th>SPZ</th>-->
                <th>Tony</th>
                <th>m<sup>3</sup></th>
                <th>Vlhkosť</th>
                <th class="col-tony-nadrozmer">Nadrozmer</th>
                <th>Doklad</th>
                <!--    <th>t v</th>-->

                <!--    <th>m3 v</th>-->
                <!--    <th>PRM m</th>-->
                <!--    <th>PRM v</th>-->

                <!--    <th>materiál typ</th>-->
                <th>Materiál</th>
                <th class="col-stav">Stav</th>
                <!--    <th class="col-chyba">chyba</th>-->
                <th class="col-upravy no-print">Úpravy</th>

            </tr>
            </thead>

            <tfoot>
            <tr>
                <!--        <th>ID</th>-->
                <!--        <th>doklad číslo</th>-->
                <th></th>
                <th>datum</th>
                <th>sklad</th>
                <th>podsklad</th>
                <th>dod</th>
                <th>prepravca</th>
                <th>SPZ</th>
                <th>t m</th>
                <th>t nadrozmer</th>
                <th>t v</th>
                <th>m3 m</th>
                <th>m3 v</th>

            </tr>
            </tfoot>


        </table>



<?php
//nastavenie gmailu pre posielanie mailov
//vsetko bezpecnostne z linku povolit

//https://support.google.com/mail/answer/14257?hl=en

//$mailTransport = new Zend_Mail_Transport_Smtp('smtp.gmail.com', array(
//    'auth'     => 'login',
//    'username' => 'foxyzv@gmail.com',
//    'password' => '64018628',
//    'port'     => '587',
//    'ssl'      => 'tls',
//));
//Zend_Mail::setDefaultTransport($mailTransport);
//
//$mail = new Zend_Mail();
//$mail->setFrom('foxyzv@gmail.com');
//$mail->setBodyHtml('some message - it may be html formatted text');
//$mail->addTo('foxyzv@gmail.com', 'recipient');
//$mail->setSubject('subject');
//$mail->send();

?>