<?php
$this->headTitle($this->title);
$this->inlineScript()->appendFile($this->baseUrl().'/js/bootstrap.min.js');
$this->inlineScript()->appendFile($this->baseUrl().'/js/jjquery.js');
$this->inlineScript()->appendFile($this->baseUrl().'/js/ajax_prijmy_errors.js');
$this->inlineScript()->appendFile($this->baseUrl().'/js/table_features_prijmy.js');
//$this->inlineScript()->appendFile($this->baseUrl().'/js/fancy_table.js');

$notifikacie     = new Application_Model_Notifikacie();
$notif_info = $notifikacie->getStatusArray();
$count_notif = $notif_info['total'];
$prijmy_w = $notif_info['prijmy_waitings'];
$prijmy_e = $notif_info['prijmy_errors'];

$controller = 'prijmy';

$this->prijmybuttons($this,$prijmy_w,$prijmy_e,$controller);

$this->tablefiltersVydaje($this, "Dodávateľ");
?>


<div id=".col-lg-12"  class="table-responsive">
    <table id="fancy_table"  class="table table-striped table-hover">

        <thead>
        <tr class="tableizer-firsrow">
            <!--    <th>ID</th>-->
            <!--        <th>doklad číslo</th>-->
            <TH class="no-print">Detail</TH>
            <th>Dátum</th>
            <th>Lokalita</th>
            <th class="col-podsklad">Sklad</th>
            <th>Dodávateľ</th>
            <th>Prepravca</th>
            <!--    <th>SPZ</th>-->
            <th>Tony</th>
            <th>m<sup>3</sup></th>
            <th>Vlhkosť</th>
            <th class="col-tony-nadrozmer">Nadrozmer</th>
            <th>Nákupná cena</th>
            <th>Predajná cena</th>
            <th>Doklad</th>
            <!--    <th>t v</th>-->

            <!--    <th>m3 v</th>-->
            <!--    <th>PRM m</th>-->
            <!--    <th>PRM v</th>-->

            <!--    <th>materiál typ</th>-->
            <th>Materiál</th>
            <th class="col-stav">Stav</th>
            <!--    <th class="col-chyba">chyba</th>-->
            <th class="col-upravy no-print">Úpravy</th>
        </tr>
        </thead>

        <tfoot>
        <tr>

            <th></th>
            <th>datum</th>
            <th>sklad</th>
            <th>podsklad</th>
            <th>dod</th>
            <th>prepravca</th>

            <th>t m</th>
            <th>t nadrozmer</th>
            <th>Nákupná cena</th>
            <th>Predajná cena</th>

                    <th>m3 m</th>

            <th>material druh</th>
                    <th></th>
                    <th>chyba</th>


        </tr>
        </tfoot>

    </table>

    <div id="tonaz">   </div>
    <div id="m3">   </div>
    <div id="priemer"> </div>
    <div id="nakupne"> </div>
    <div id="predajne"> </div>

</div>