<h2>Motohodiny - odstránenie</h2>
<div class="col-lg-5">
    <div class="panel panel-red">
        <div class="panel-heading">
            <h3 class="panel-title">Odstránenie motohodiny</h3>
        </div>
        <div class="panel-body">

            <div class="row">
                <fieldset>
                    <legend>Stroj</legend>
                    <div class="col-lg-6">

                        <?php echo $this->strojeModel->getNazov($this->motohodina['stroj_enum']);?>
                    </div>
                    <legend>Obdobie</legend>
                    <div class="col-lg-6">
                        <?php echo $this->rokyModel->getNazov($this->motohodina['rok_enum']).".".$this->mesiaceModel->getNazov($this->motohodina['mesiac_enum']);?>
                    </div>
                    <legend>Počet hodín</legend>
                    <div class="col-lg-6">
                        <?php echo number_format($this->motohodina['pocet_hodin'], 2, ",", " ");?>
                    </div>
                </fieldset>
            </div>
            <br>
            <div class="row">
                <form action="<?php echo $this->url(array('action'=>'delete', 'fromAction' => $this->fromAction)); ?>"
                      method="post">
                        <div>
                            <input type="hidden" name="id" value="<?php echo $this->motohodina['motohodiny_id']; ?>" />
                            <div class="col-lg-6 tright">
                            <input type="submit" name="del" value="Áno" class="btn btn-danger"/></div>
                                <div class="col-lg-6">
                            <input type="submit" name="del" value="Nie" class="form-control btn-warning btn"/>
                                    </div>
                        </div>
                </form>
            </div>

        </div>
    </div>








