<h2>Mikroobjednávky - odstránenie</h2>
<div class="col-lg-5">
    <div class="panel panel-red">
        <div class="panel-heading">
            <h3 class="panel-title">Odstránenie mikroobjednávky</h3>
        </div>
        <div class="panel-body">

            <div class="row">
                <fieldset>
                    <legend>Zákazník</legend>
                    <div class="col-lg-6">

                        <?php echo $this->zakazniciModel->getNazov($this->mikroObjednavka['zakaznik_enum']);?>
                    </div>
                    <legend>Obdobie</legend>
                    <div class="col-lg-6">
                        <?php echo "Od ". date("d.m.Y", strtotime($this->mikroObjednavka['datum_od_d'])) ." do ".date("d.m.Y", strtotime($this->mikroObjednavka['datum_do_d'])) ;?>
                    </div>
                    <legend>Objednané množstvo</legend>
                    <div class="col-lg-6">
                        <?php echo number_format($this->mikroObjednavka['mnozstvo'], 2, ",", " ")." ".$this->merneJednotkyModel->getSkratka($this->mikroObjednavka['merna_jednotka_enum']);?>
                    </div>
                </fieldset>
            </div>
            <br>
            <div class="row">
                <form action="<?php echo $this->url(array('action'=>'delete', 'fromAction' => $this->fromAction)); ?>"
                      method="post">
                        <div>
                            <input type="hidden" name="id" value="<?php echo $this->mikroObjednavka['objednavky_mikro_id']; ?>" />
                            <div class="col-lg-6 tright">
                            <input type="submit" name="del" value="Áno" class="btn btn-danger"/></div>
                                <div class="col-lg-6">
                            <input type="submit" name="del" value="Nie" class="form-control btn-warning btn"/>
                                    </div>
                        </div>
                </form>
            </div>

        </div>
    </div>








