<h2 >Spotreby - detail</h2>
<!--<hr>-->
<div class="col-lg-5">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title"><i class="fa fa-minus-square"></i> Detail spotreby  <?php echo $this->spotreba['doklad_cislo'];?></h3>
		</div>
		<div class="panel-body">

			<div class="row">
				<fieldset>
					<legend><i class="fa fa-calendar"></i> Dátum spotreby</legend>

					<div class="col-lg-6">
						Dátum:
						<?php echo date("d.m.Y", strtotime($this->spotreba['datum_spotreby_d']));?>
					</div>
				</fieldset>
			</div>

			<div class="row">
				<fieldset>
					<legend><i class="fa fa-bank"></i> Sklady</legend>
					<div class="col-lg-6">
						Lokalita:

						<?php echo $this->ciselniky['skladyModel']->getNazov($this->spotreba['sklad_enum']); // render the user name field here ?>
					</div>

					<div class="col-lg-6">
						Sklad:
						<?php echo $this->ciselniky['podskladyModel']->getNazov($this->spotreba['podsklad_enum']); // render the user name field here ?>
					</div>
				</fieldset>
			</div>


			<div class="row">
				<fieldset>
					<legend><i class="fa fa-truck"></i> Dodanie</legend>
					<div class="col-lg-6">
						Zákazník:
						<?php echo $this->ciselniky['zakazniciModel']->getNazov($this->spotreba['zakaznik_enum']); // render the user name field here ?>
					</div>
				</fieldset>
			</div>


			<div class="row">
				<fieldset>
					<legend><i class="fa fa-cubes"></i> Množstvo</legend>
					<div class="col-lg-6">
						Váha:
						<?php echo number_format($this->spotreba['q_tony_merane'], 2, ",", " ").' t'; // render the user name field here ?>
					</div>


					<div class="col-lg-6">
						Objem:
						<?php echo number_format($this->spotreba['q_m3_merane'], 2, ",", " ").' m<sup>3</sup>'; // render the user name field here ?>
					</div>

			</div>
			<div class="row">


				<div class="col-lg-6">
					Priestor:
					<?php echo number_format($this->spotreba['q_prm_merane'], 2, ",", " ").' PRM'; // render the user name field here ?>
				</div>
				<div class="col-lg-6">
					Vlhkosť:
					<?php echo number_format($this->spotreba['q_vlhkost'], 2, ",", " ").' %'; // render the user name field here ?>
				</div>
				</fieldset>
			</div>


			<div class="row">
				<fieldset>
					<legend><i class="fa fa-tree"></i> Materiál</legend>
					<div class="col-lg-6">
						Typ:
						<?php echo $this->ciselniky['materialyTypyModel']->getNazov($this->spotreba['material_typ_enum']); // render the user name field here ?>
					</div>
					<div class="col-lg-6">
						Druh:
						<?php echo $this->ciselniky['materialyDruhyModel']->getNazov($this->spotreba['material_druh_enum']); // render the user name field here ?>
					</div>

			</div>


			<div class="row">
				<fieldset>
					<legend><i class="fa fa-info-circle"></i> Doplňujúce informácie</legend>
					<div class="col-lg-6">
						Stav:
						<?php echo $this->ciselniky['transakcieStavyModel']->getNazov($this->spotreba['stav_transakcie']); // render the user name field here ?>
					</div>
					<div class="col-lg-6">
						Chyba:
						<?php if ($this->spotreba['chyba'] == 1 ) echo 'áno';
						else echo 'nie'; // render the user name field here ?>
					</div>
			</div>
			<br>
			<div class="row">

				<div class="col-lg-12">
					Poznámka:
					<?php if ($this->spotreba['poznamka'] == '' || $this->spotreba['poznamka'] == '0' ) echo 'žiadna poznámka';
					else echo $this->spotreba['poznamka']; // render the user name field here ?>
				</div>
				</fieldset>
			</div>



			<br>

			<div class="row">


				<div class="col-lg-6 tright">
					<!--                    <a href="--><?php //echo $this->url(array('controller'=>'spotrebae',
					//                        'action'=>'print', 'ts_spotrebae_id'=>$this->spotreba['ts_spotrebae_id'], 'cislo_listku'=>$spotreba->doklad_cislo,
					//                        'spz'=>$spotreba->prepravca_spz));?><!--" target="_blank" class="btn-info btn" >-->
					<!--                                --><?php //echo '<img src="'.$this->baseUrl().'/images/tlacit.png" alt="tlacit">'; ?>
					<!--                        Tlačiť-->
					<!--                    </a>-->

					<?php

					$merna_jednotka = $this->ciselniky['zakazniciModel']->getMernaJednotka($this->spotreba['zakaznik_enum']);

					if ($merna_jednotka == 1 )
						echo '<a class="btn-info btn" href="'.$this->url(array("controller"=>"spotrebae", "action"=>"printton", "id"=>$this->spotreba['ts_spotrebae_id'], "fromAction" => "list",
								)).'" target="_blank">Tlačiť</a>'
					//                <!--                    printton-->
					?>

					<?php  if ($merna_jednotka == 2 )
						echo '<a class="btn-info btn" href="'.$this->url(array("controller"=>"spotrebae", "action"=>"printprm", "id"=>$this->spotreba['ts_spotrebae_id'], "fromAction" => "list",
								)).'" target="_blank">Tlačiť</a>'
					//                <!--                   printprm-->
					?>
					<?php  if ($merna_jednotka == 3 )
						echo '<a class="btn-info btn" href="'.$this->url(array("controller"=>"spotrebae", "action"=>"printm3", "id"=>$this->spotreba['ts_spotrebae_id'], "fromAction" => "list",
								)).'" target="_blank">Tlačiť</a>'
					//                <!--                    printm3-->
					//                                ?>



				</div>

				<div class="col-lg-6">
					<a href="<?php echo $this->url(array(
							'controller' => $this->fromController,
							'action' => $this->fromAction,
							'id' => $this->fromId
					), null, true) ?>"  type="button" class="btn btn-warning form-control">Späť</a>
				</div>



			</div>

		</div>
	</div>